project:
  type: website
  output-dir: _site


website:
  title: "Lost in solution"
  site-url: "https://joschwrzr.github.io/CO2_lost_in_solution/"
  navbar:
    left:
      - text: "About"
        href: About.qmd
      - text: "Correction Factors"
        href: CorrectionFactors.qmd
      - text: "Gas exchange kinetics"
        href: Kinetics.qmd
      - text: "more"
        menu: 
          - Abbreviations.qmd

      

      
author: "Petr Čapek & Johanna Schwarzer"

# Enable search
search: true

format:
  html:
    theme: 
      light: minty
      dark: solar
    toc: true
    toc-location: left

    
    



