{
  "hash": "20ed92b616f25056449a63199498239c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"CO2_web\"\nformat: html\neditor: visual\n---\n\n\n\n\n\n\n\n# Applying ideal gas law\n\nAll the calculations begin with the ideal gas law:\n\n$$p \\times V = n \\times R \\times T \\hspace{75mm}(eq. 1),$$\n\nwhere $p$ is pressure, $V$ is volume, $n$ is number of moles of ideal gas, $R$ is universal gas constant, and $T$ is temperature. The first key consideration is ensuring unit comparability. If we arbitrarily select $R = 8.314 \\frac{J}{mol \\times K}$, $T$ must be in Kelvins (K), $n$ in moles, $p$ in Pascals (Pa), and $V$ in cubic meters ($m^{3}$) since the derived units joules and pascals are defined as $J = \\frac{kg \\times m^{2}}{s^{2}}$ and $Pa = \\frac{kg}{m \\times s^{2}}$, respectively:\n\n$$\\frac{kg}{m \\times s^{2}}(p) \\times m^{3}(V) = mol(n) \\times  \\frac{kg \\times m^{2}}{s^{2} \\times mol \\times K}(R) \\times K(T) \\Longrightarrow \\frac{kg \\times m^2}{s^2} = \\frac{kg \\times m^2}{s^2}  \\hspace{10mm}(eq. 2).$$\n\nIt may be convenient to redefine the units to express volume of container headspace in mL instead of cubic meters and express the gas pressure in atmospheres instead of Pascals. At the see level, atmospheric pressure is 1 atmosphere (atm), which is a very convenient number. If we choose to use atm as the unit of pressure, the value of universal gas constant $R$ must be expressed as $R = 0.082 \\frac{L \\times atm}{mol \\times K}$. Furthermore, by expressing $V$ in the more convenient unit of mL while keeping K as the unit of temperature, $n$ will be expressed in mmol.\n\nSince we are interested in concentration of $CO_{2}$ in the headspace of closed container, eq. 1 is solved in respect to $n$:\n\n$$n = \\frac{p \\times V}{R \\times T}  \\hspace{75mm}(eq. 3).$$\n\nEquation 3 applies to all gases in the entire headspace of the container. However, we are only interested in $CO_{2}$, which occupies a fraction of the headspace. Gas chromatography typically returns the concentration of headspace $CO_{2}$ in ppm (parts per million). It is convenient to define a new variable $\\beta$ representing the measured $CO_{2}$ concentration in ppm. For example, if $\\beta$ is e.g. 450 ppm at the beginning of an incubation, then the partial pressure of $CO_{2}$ (usually denoted as $pCO_{2}$) in the headspace of a container that has been closed at atmospheric pressure 1 atm is then $\\beta \\times 10^{-6} \\times p = 450 \\times 10^{-6} \\times 1 = 0.000450~atm~(pCO_{2})$. The partial pressure of $CO_{2}$ in atm is function of $CO_{2}$ concentration in ppm and pressure in atm. Since gas chromatography usually returns $CO_{2}$ concentration in ppm, we will use variable $\\beta$ in all equations below rather than $pCO_{2}$. If the container's headspace volume is e.g. 100 mL and the container is held at a temperature of $20°C = 20 + 273.15 = 293.15 K$, the headspace $CO_{2}$ concentration is:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"beta-label\" for=\"beta\">Headspace CO<sub>2</sub> concentration in ppm:</label>\n<input id=\"beta\" type=\"number\" class=\"shiny-input-number form-control\" value=\"450\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"p-label\" for=\"p\">Atmospheric pressure (p) in atm:</label>\n<input id=\"p\" type=\"number\" class=\"shiny-input-number form-control\" value=\"1\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature (T) in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"out2c54d99dde6ec802\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$~$\n\n$$CO_{2}[mmol] = \\frac{450[ppm] \\times 10^{-6} \\times 1[atm] \\times 100[mL]}{0.082[\\frac{L \\times atm}{mol \\times K}] \\times 293.15[K]}=0.0019~mmol = 1.9~ \\mu mol  \\hspace{10mm}(eq. 4).$$\n\n$~$\n\nA change in partial pressure of $CO_{2}$ in the headspace translates to change in $CO_{2}$ concentration. If the $\\beta$ increases to e.g. $10^4$ ppm after one week of incubation, the change in $CO_{2}$ concentration can be calculated using the same approach as for the initial $CO_{2}$ concentration. The only difference is that $\\Delta \\beta$ (i.e. $10^4 - 450$) is used instead of $\\beta$:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"D_beta-label\" for=\"D_beta\">Headspace CO<sub>2</sub> concentration change in ppm:</label>\n<input id=\"D_beta\" type=\"number\" class=\"shiny-input-number form-control\" value=\"9550\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"p-label\" for=\"p\">Atmospheric pressure (p) in atm:</label>\n<input id=\"p\" type=\"number\" class=\"shiny-input-number form-control\" value=\"1\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature (T) in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"out7b4239d7a14d21a3\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$~$\n\n$$\\Delta CO_{2}[mmol] = \\frac{(10^4 - 450)[ppm] \\times 10^{-6} \\times 1[atm] \\times 100[mL]}{0.082[\\frac{L \\times atm}{mol \\times K}] \\times 293.15[K]}=0.0397~mmol = 30.97~ \\mu mol  \\hspace{10mm}(eq. 5).$$\n\n$~$\n\nThis results can be normalized to a unit of oven dried soil and time. It is important to note that all other variables stay the same.\n\nAlthough the procedure may seem straightforward, **several aspects require careful attention**. In following sections, we will gradually discuss quantitatively the most important aspects - headspace pressure change and $CO_2$ dissolution as affected by temperature, volume of soil solution, its acidity/alkalinity and ionic strength.\n\n### Change of headspace pressure\n\nLaboratory incubations are almost always performed at constant temperature so the variable $T$ in all equations above is well defined. However, a potential issue arises if the incubation temperature differs from the temperature at which the container was sealed (typically room temperature), as this leads to a change in headspace pressure due to thermal expansion or contraction of the gas. The effect of temperature change on pressure change can be calculated using eq. 1. $V$ of the container does not change and, for simplicity, $n$ can be considered constant for some brief period of time. Any change of $T$ must be compensated by the change of $p$:\n\n$$\\frac{p_1}{T_1} = \\frac{p_2}{T_2} \\hspace{75mm} (eq. 6).$$\n\nThe change of $p$ from $p_1$, previously defined as 1 atm, to $p_2$ can be expressed as a function of $T_1$ and $T_2$:\n\n$$\\Delta p = p_2 - p_1 = p_1 \\times (\\frac{T_2}{T_1} - 1) \\hspace{75mm} (eq. 7).$$\n\nIf the container is closed at a room temperature of $20°C = T_1 = 293.15K$ and then stored in an incubator set to $30°C = T_2 = 303.15K$, the headspace pressure change is:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"T1-label\" for=\"T1\">Temperature at which the container was closed in K (T<sub>1</sub>):</label>\n<input id=\"T1\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"T2-label\" for=\"T2\">Incubation temperature in K (T<sub>2</sub>):</label>\n<input id=\"T2\" type=\"number\" class=\"shiny-input-number form-control\" value=\"303.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"p-label\" for=\"p\">Atmospheric pressure (p) at which the container was closed in atm:</label>\n<input id=\"p\" type=\"number\" class=\"shiny-input-number form-control\" value=\"1\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"outf176a468ff39c659\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$~$\n\n$$\\Delta p = 1 \\times (\\frac{303.15}{293.15} - 1) = 0.034~atm \\hspace{75mm} (eq. 8).$$\n\n$~$\n\nWhen the $CO_2$ concentration is calculated using Eq. 5, and the headspace pressure is assumed to remain equal to atmospheric pressure (1 atm), in other words, that $\\Delta p = 0$, results will be inaccurate. To correct for the change in temperature, the overpressure, defined by the term $(\\frac{T_2}{T_1} - 1)$ can be released so that $p_2 = p_1$, or the result of Eq. 5 is calculated only with values of $p_1$ (1 atm) and $T_2$ (303.15 K).\n\n$$\\Delta CO_{2}(\\Delta p=0) = \\frac{\\beta \\times 10^{-6} \\times p_1 \\times V}{R \\times T_2} \\hspace{75mm} (eq. 9).$$\n\nIf $T_2$ differs from $T_1$ and the pressure changed, we need to use $p_2$, which is a function of $p_1$, $T_1$ and $T_2$ ($p_2 = p_1 \\times \\frac{T_2}{T_1}$):\n\n$$\\Delta CO_{2}(\\Delta p \\neq 0) = \\frac{\\beta \\times 10^{-6} \\times p_1 \\times \\frac{T_2}{T_1} \\times V}{R \\times T_2} \\hspace{75mm} (eq. 10).$$\n\nThe relative error associated with disregarding the pressure change induced by a change in $T$ can be defined with respect to $\\Delta CO_{2}(\\Delta p \\neq 0)$ for example using the following equation that combines eqs. 5 and 10:\n\n$$Error (\\%) = (\\frac{\\Delta CO_{2}(\\Delta p=0)}{\\Delta CO_{2}(\\Delta p \\neq 0)}-1) \\times 100 = (\\frac{T_1}{T_2}-1) \\times 100 \\hspace{75mm} (eq. 11).$$\n\nIf $\\frac{T_1}{T_2} = \\frac{293.15}{303.15}$, the relative error in the calculated $CO_2$ concentration due to the invalid assumption that the headspace pressure remains constant is:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"T1-label\" for=\"T1\">Temperature at which the container was closed in K (T<sub>1</sub>):</label>\n<input id=\"T1\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"T2-label\" for=\"T2\">Incubation temperature in K (T<sub>2</sub>):</label>\n<input id=\"T2\" type=\"number\" class=\"shiny-input-number form-control\" value=\"303.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"outf12354fbb2011e84\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$~$\n\n$$Error (\\%) = (\\frac{293.15}{303.15}-1) \\times 100 = -3.3 \\% \\hspace{75mm} (eq. 12).$$\n\n$~$\n\nOur result is underestimated by approx. 3%. If the $T_2$ is lower than $T_1$, e.g. the temperature in incubation vessel is lowered to $5°C = 278.15K$, the relative error is $(\\frac{293.15}{273.15}-1) \\times 100 = 5.4 \\%$ thus, the result is slightly overestimated. An underestimation of the result by 10% is achieved when incubation temperature $T_2$ is around 50°C.\\\nThe pressure in the headspace can be also affected by unbalanced exchange of gasses between the soil and headspace. In aerobic incubations, $CO_2$ production is frequently assumed to be perfectly balanced by $O_2$ consumption, i.e. there is one mole of consumed $O_2$ per one mole of produced $CO_2$. However, this 1:1 ratio, so called respiration quotient, is not always reached even under aerobic conditions. It could be as high as 1.75 or close to 0.1 (Dilly, 2001, 2003 and 2004, Capek et al., 2015). Ratio higher than 1 causes increase of pressure and vice versa. Great change in headspace pressure could be expected in anaerobic incubations as the increase in $CO_2$ concentration is not compensated for by the $O_2$ consumption. The effects of respiration quotient other than 1 and anaerobiosis on headspace pressure change is beyond the scope of this document so it will not be discussed further.\n\n#### Example: Temperature sensitivity of respiration (case 1)\n\nThe sensitivity of soil respiration to temperature was commonly expressed as a $Q_{10}$, i.e. a parameter which defines the relative change in respiration (i.e. change in $pCO_2$ in the vessel) with a temperature change of 10°C:\n\n$$Q_{10} = \\frac{\\Delta CO_2(T_2)}{\\Delta CO_2(T_1)}^{\\frac{10}{T_2 - T_1}} \\hspace{75mm} (eq. 13).$$\n\nWe will arbitrarily select $Q_{10}$ 2, i.e. $\\Delta CO_2(T_2)$ is 2 times greater than $\\Delta CO_2(T_1)$ when $T_2 - T_1 = 10°C$. Even though the $Q_{10}$ concept is nowadays considered inaccurate, its relative simplicity will allow us to easily quantify the error caused by headspace pressure change. If $T_2 - T_1 = 10°C$, $Q_{10}$ can simply be calculated using respiration measured at two different temperatures. We can simply assume that $T_1$ is laboratory temperature 20°C and $T_2$ is then 30°C. Using two measured respiration rates, calculated $Q_{10}$ was experimentally estimated to be 2. However, the headspace pressure change was ignored when respiration at 30°C was calculated. If the respiration is recalculated applying eq. 6, $Q_{10}$ changes from 2 to:\n\n$$Q_{10} = 2 \\times \\frac{T_2}{T_1} = 2 \\times \\frac{393.15}{293.15} = 2.07 \\hspace{75mm} (eq. 14).$$\n\nThis change represents the relative error of 3.5%.\n\n# Dissolution of $CO_2$ in acidic soils\n\nThe headspace $CO_2$ represents only a fraction of the total inorganic carbon (IC) in a closed incubation container with a soil sample. This is because $CO_2$ is soluble and can dissolve in soil water. If the dissolved $CO_2$ is ignored, the respiration rate calculated from $\\Delta \\beta$ (eq. 5) may be underestimated. The dissolution process is governed by the following equilibrium reaction:\n\n$$CO_2(gas) \\rightleftarrows CO_2(aq)^{*} \\hspace{75mm} (eq. 15).$$\n\nAccording to Henry's law, the $CO_2$ dissolved in (soil) water as $CO_2(aq)^{*}$ (here $CO_2(aq)^{*}$ represents the sum of $CO_2(aq)$ and $H_2CO_3$) is proportional to the partial pressure of $CO_2$ in the container's headspace, which is $\\Delta \\beta \\times 10^{-6} \\times p$ in eq. 4. We assume that there is an equilibrium between the two forms of IC (see below). At that equilibrium, $CO_2(aq)^{*}$ can be calculated from measured $\\beta$ using an equation:\n\n$$CO_2(aq)^{*} = K_H \\times \\beta \\times 10^{-6} \\times p  \\hspace{75mm} (eq. 16),$$\n\nin which $K_H$ is Henry's law constant in $\\frac{mol}{L \\times atm}$ of the reaction described by eq. 15. Eq. 16 was simplified to allow a straightforward calculation.\n\nEq. 16 is frequently transformed by a decadic logarithm and $K_H$ is expressed as $pK_H$:\n\n$$log(CO_2(aq)^{*}) = pK_H + log(\\beta \\times 10^{-6}) + log(p) \\hspace{75mm} (eq. 17).$$\n\n$pK_H$ is an experimentally derived constant, which is temperature dependent. According to Plummer and Busenberg (1982), the relationship between $pK_H$ and T (in K again) is:\n\n$$pK_H = 108.3865 + 0.01985076 \\times T - 6919.53 \\times \\frac{1}{T} - 40.45154 \\times log(T) + 669356 \\times \\frac{1}{T^2} \\hspace{75mm} (eq. 18).$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![***Figure 1***: *Relationship between the temperature and Henry's law constant $pK_H$ for $CO_2$.*](respiration_files/figure-html/Rscript (5) plotting pK0 against T according to eq. 18-1.png){width=672}\n:::\n:::\n\n\nAs shown in figure 1, $pK_H$ decreases (within values -1.109 and -1.711) with increasing temperature between 0 and 50°C (i.e. 273.15 and 323.15K). This means that the solubility of $CO_2$ in water decreases with increasing temperature.\n\nKnowing the experimentally derived value of $pK_H$, the concentration of $CO_2(aq)^{*}$ in soil solution (in moles of $CO_2(aq)^{*}$ per liter) can be calculated. However, our interest lies not in concentration, but in the absolute amount of $CO_2(aq)^{*}$ within the closed container. This allows direct comparison to the amount of $CO_2$ in the headspace calculated by eqs. 4 and 5. To obtain the absolute amount of $CO_2(aq)^{*}$ in moles, the $CO_2(aq)^{*}$ concentration in $mol \\times L^{-1}$ is multiplied by the volume of soil water in mL ($V_s$). The result is then in mmols (i.e. 1 mole of $CO_2(aq)^{*}$ contains 1 mole of IC.\n\nLet's assume that we incubate 10 grams of fresh organic soil with a pH around 4. The soil was collected from organo-mineral horizon of spruce forest ecosystem and its relative dry weight content is 0.2. The volume of soil water is therefore 8 mL ($10 g \\times (1 - 0.2) = 8 g = 8 mL$).The amount of $CO_2(aq)^{*}$ in the soil water at 20°C (293.15K), a headspace pressure of 1 atm and an initial $CO_2$ concentration of 450 ppm is:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs-label\" for=\"Vs\">Volume of soil water (V<sub>s</sub>) in mL:</label>\n<input id=\"Vs\" type=\"number\" class=\"shiny-input-number form-control\" value=\"8\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature (T) in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"p-label\" for=\"p\">Atmospheric pressure (p) in atm:</label>\n<input id=\"p\" type=\"number\" class=\"shiny-input-number form-control\" value=\"1\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"beta-label\" for=\"beta\">Headspace CO<sub>2</sub> concentration in ppm:</label>\n<input id=\"beta\" type=\"number\" class=\"shiny-input-number form-control\" value=\"450\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"outa2cd59fb62ed7aab\" class=\"shiny-html-output\"></div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"outeab6f238c5bf56a4\" class=\"shiny-html-output\"></div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"out7389850d655f7492\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$~$\n\n$$CO_2(aq)^{*} = 10^{pK_H} \\times 450~ppm \\times 10^{-6} \\times 8~mL = 1.41 \\times 10^{-4} ~ mmol = 0.14~ \\mu mol \\hspace{75mm} (eq. 19).$$\n\nwhere\n\n$$pK_H = 108.3865 + 0.01985076 \\times 293.15 - 6919.53 \\times \\frac{1}{293.15} - 40.45154 \\times log(293.15) + 669356 \\times \\frac{1}{293.15^2} = -1.41 \\hspace{75mm} (eq. 20).$$\n\n$~$\n\nIn this example, 0.14 µmol of inorganic carbon (IC) in the form of $CO_2(aq)^{*}$ is dissolved in the soil water. If this dissolved $CO_2(aq)^{*}$ is not accounted for in the calculation, the resulting estimate of $CO_2$ production is underestimated by 7.5%. Since $pK_H$ is temperature sensitive, it may be interesting to calculate the proportion between $CO_2(aq)^{*}$ and $CO_2$ at 0°C (273.15K). This can be done by changing the temperature from 293.15 to 273.15 in the boxes above. The calculation reveals that at 0°C, $CO_2(aq)^{*}$ makes up 14% of headspace $CO_2$.\n\n### Quantitative importance of $CO_2$ dissolution in acidic soils\n\nThe two most important factors that affect how much $CO_2(aq)^{*}$ can dissolve in the aqueous phase of the soil sample in a closed container are soil water volume and temperature. This can be defined quantitatively.\n\n-   **Soil water content**\n\nAt a constant temperature, e.g. 20°C, the relative proportion between $CO_2(aq)^{*}$ and $CO_2$ in % can be easily expressed when eqs. 4 (ideal gas law) and 16 are combined:\n\n$$\\frac{CO_2(aq)^{*}}{CO_2} \\times 100 = 10^{pK_H} \\times \\beta \\times 10^{-6} \\times p \\times V_s \\times \\frac{R \\times T}{ \\beta \\times 10^{-6} \\times p \\times V} \\times 100= 10^{pK_H} \\times R \\times T \\times \\frac{V_s}{V} \\times 100 \\hspace{10mm} (eq. 21).$$\n\nBecause $10^{pK_H}$, $R$ and $T$ are constant and the product of their multiplication at 20°C is always 0.94, the relative proportion between $CO_2(aq)^{*}$ and $CO_2$ is entirely defined by the ratio of soil water volume to headspace volume, both being in mL. If the \\$ \\frac{V_s}{V} = \\frac{8}{100} = 0.08\\$ as in eqs. 5 and 19, the result of eq. 21 is $0.94 \\times  \\frac{8}{100} \\times 100 = 7.5 \\%$. The functional relationship between $\\frac{V_s}{V}$ and $\\frac{CO_2(aq)^{*}}{CO_2} \\times 100$ is shown in the graph below:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![***Figure 2***: *Relationship between the relative amount of $CO_2(aq)^{*}$ per $CO_2(gas)$ and relative volume of soil water $V_s$ in respect to headspace volume $V$ in a closed cotainer*](respiration_files/figure-html/Rscript (7) Applying eq 21-1.png){width=672}\n:::\n:::\n\n\nFigure 2 shows that with increasing water content in the incubated soil sample relative to the gas headspace of the incubation container, the fraction of $CO_2(aq)^{*}$ increases. This means that, **with increasing water content, the estimated total inorganic carbon (IC) in the container is underestimated if the water-soluble fraction of IC is ignored**.\n\n-   **Temperature**\n\nThe effect of temperature on $CO_2(aq)^{*}$ is more complex as $T$ affects the $CO_2$ headspace concentration (eq. 3) and $pK_H$ (eq. 17). When we plot the effect of temperature as we did for the effect of water content in figure 2, the slope of the linear relationship decreases with increasing temperature. This means that **the amount of IC in the water phase of the sample increases with decreasing temperatures**. The following graph shows the relationship between $\\frac{V_s}{V}$ and $\\frac{CO_2(aq)^{*}}{CO_2}$ at the three different temperatures - 0, 20 and 30°C:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![***Figure 3***: *Relationship between the relative amount of $CO_2(aq)^{*}$ $CO_2(gas)$ and relative volume of soil water $V_s$ in respect to headspace volume $V$ in a closed cotainer incubated at three different temperatures 0, 20 and 30°C*](respiration_files/figure-html/Rscript (8) Applying eq 21-1.png){width=672}\n:::\n:::\n\n\nIgnoring $CO_2$ dissolution has little effect on the calculated respiration rates in acidic soils with low moisture, large headspace, and high temperature. However, respiration is likely underestimated due to high $CO_2$ solubility in wet soils or peat samples incubated in small containers at low temperatures.\n\n#### Example: Temperature sensitivity of respiration (case 2)\n\nIn the following we will extend the effect of headspace pressure change on temperature sensitivity in case 1 for the effect of $CO_2$ dissolution in acidic soil water, including the temperature sensitive $pK_H$. To do so, we combine eq. 13 with the ideal gas law (eq. 3), for two different temperatures $T_1$ and $T_2$ (whose difference is 10°C again). We can to express the apparent $Q_{10}^{app}$ as a function of $\\Delta \\beta_1$ and $\\Delta \\beta_2$ measured at the GC for $T_1$ and $T_2$:\n\n$$Q_{10}^{app} = \\frac{\\Delta CO_2(T_2)}{\\Delta CO_2(T_1)} = \\frac{\\frac{\\Delta \\beta_2 \\times 10^{-6} \\times p \\times V}{R \\times T_2}}{\\frac{\\Delta \\beta_1 \\times 10^{-6} \\times p \\times V}{R \\times T_1}} = \\frac{\\Delta \\beta_2}{\\Delta \\beta_1} \\times \\frac{T_1}{T_2} = 2 \\hspace{10mm} (eq. 22).$$\n\nWe assume that $Q_{10}^{app}$ is 2. Now, we will calculate the true $Q_{10}$ that considers all forms of IC in our closed incubation container, i.e. $CO_2$ and $CO_2(aq)^{*}$. To do so, $Q_{10}$ is calculated using following equation:\n\n$$Q_{10} = \\frac{\\Delta CO_2(T_2) + \\Delta CO_2(aq)^{*}(T_2)}{\\Delta CO_2(T_1) + \\Delta CO_2(aq)^{*}(T_1)} = \\frac{\\Delta \\beta_2}{\\Delta \\beta_1} \\times \\frac{\\frac{V}{R \\times T_2} + 10^{pK_H(T_2) \\times V_s}}{\\frac{V}{R \\times T_1} + 10^{pK_H(T_1) \\times V_s}} \\hspace{10mm} (eq. 23).$$\n\nBy combining eqs. 22 and 23, we obtain the following equation:\n\n$$Q_{10} = Q_{10}^{app} \\times \\frac{T_2}{T_1} \\times \\frac{\\frac{V}{R \\times T_2} + 10^{pK_H(T_2) \\times V_s}}{\\frac{V}{R \\times T_1} + 10^{pK_H(T_1) \\times V_s}} \\hspace{10mm} (eq. 24).$$\n\n$Q_{10}$ is first calculated for a scenario with $V = 100mL$, $V_s = 8 mL$, $T_1$ and $T_2$ are 20 and 30°C, respectively:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs-label\" for=\"Vs\">Volume of soil water (V<sub>s</sub>) in mL:</label>\n<input id=\"Vs\" type=\"number\" class=\"shiny-input-number form-control\" value=\"8\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp1-label\" for=\"Temp1\">Temperature 1 (T<sub>1</sub>) in K:</label>\n<input id=\"Temp1\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp2-label\" for=\"Temp2\">Temperature 2 (T<sub>2</sub>) in K:</label>\n<input id=\"Temp2\" type=\"number\" class=\"shiny-input-number form-control\" value=\"303.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"out7e5f537e40446b74\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$$Q_{10} = 2 \\times \\frac{303.15}{293.15} \\times \\frac{\\frac{100}{0.082 \\times 303.15} + 10^{-1.52}\\times 8}{\\frac{100}{0.082 \\times 293.15} + 10^{-1.41 }\\times 8} = 1.97 \\hspace{10mm} (eq. 25).$$\n\nHere, $Q_{10}$ is lower than $Q_{10}^{app}$. The boxes above can be modified to calculate any other scenario. For example, if $T_1$ and $T_2$ are 0 and 10°C, respectively, $Q_{10}$ becomes 1.93. If $V_s$ is only 1 mL, $Q_{10}$ is 2. If we further acknowledge pressure change due to transfer of closed container from 20 to 30°C, $Q_{10}=1.97$ is further multiplied by $\\frac{303.15}{293.15}$, and we obtain $Q_{10}=2.04$, which is higher than $Q_{10}^{app}$.\n\n# Dissolution of $CO_2$ in neutral and alkaline soils\n\nWhen the soil solution is neutral or even alkaline (pH\\>6.5), the dissolved $CO_2(aq)^{*}$ will further dissociate to $HCO_3^{-}$ and $CO_3^{-2}$ according to following reaction formulas (keep in mind that $CO_2(aq)^{*}$ is defined as sum of $CO_2(aq)$ and $H_2CO_3$):\n\n$$CO_2(aq)^{*} ~ or ~ H_2CO_3 \\rightleftarrows H^+ + HCO_3^- \\hspace{75mm} (eq. 26),$$\n\n$$HCO_3^- \\rightleftarrows H^+ + CO_3^{-2} \\hspace{75mm} (eq. 27).$$\n\nIn this case, the IC in the soil water is no longer in equilibrium with gaseous $CO_2$ alone, but also with $H^+$, whose concentration define the pH. The respective equilibria are defined as:\n\n$$K_1 = \\frac{H^+ \\times HCO_3^-}{CO_2(aq)^{*}} \\hspace{75mm} (eq. 28),$$\n\n$$K_2 = \\frac{H^+ \\times CO_3^{-2}}{HCO_3^-} \\hspace{75mm} (eq. 29).$$\n\nBoth equations can be again transformed by decadic logarithm. Defining $pH$ as $-log(H^+)$ and expressing the decadic logarithm of $K_1$ and $K_2$ as $pK_1$ and $pK_2$, respectively, we get two equations that allow us to calculate concentrations of $HCO_3^-$ and $CO_3^{-2}$:\n\n$$log(HCO_3^-) = pK_1 + pH + log(CO_2(aq)^{*}) \\hspace{75mm} (eq. 30),$$\n\n$$log(CO_3^{-2}) = pK_2 + pH + log(HCO_3^-) \\hspace{75mm} (eq. 31).$$\n\nEqs. 30 and 31 imply that **concentration of both IC species, bicarbonate (**$HCO_3^-$) and carbonate ($CO_3^{-2}$), increases with increasing soil pH. If the concentration of $CO_2(aq)^{*}$ is known (calculated by eq. 17) and soil pH is measured, the concentration of both forms of IC can be calculated. This requires knowledge of the two equilibrium constants, $pK_1$ and $pK_2$, whose values are temperature dependent (Plummer and Busenberg (1982)):\n\n$$pK_1 = -356.3094 - 0.0601964 \\times T + 21834.37 \\times \\frac{1}{T} + 126.8339 \\times log(T) - 1684915 \\times \\frac{1}{T^2} \\hspace{35mm} (eq. 32),$$\n\n$$pK_2 = -107.8871 - 0.03252849 \\times T + 5151.79 \\times \\frac{1}{T} + 38.92561 \\times log(T) - 563713.9 \\times \\frac{1}{T^2}  \\hspace{35mm} (eq. 33).$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![***Figure 4***: *Relationship between the temperature and equilibrium constants $pK_1$ and $pK_2$*](respiration_files/figure-html/Rscript (10) plotting pK1 and pK2 against T according to eqs. 32 and 33-1.png){width=672}\n:::\n:::\n\n\nConversely to $pK_H$, $pK_1$ and $pK_2$ increase with increasing temperature. $pK_2$ is always lower than $pK_1$\n\nWe can now calculate the concentrations of all IC forms in a closed incubation container using the following equations:\n\n***Gaseous*** $CO_2$ (directly measured)\n\n$$CO_2[mmol] = \\frac{\\beta \\times 10^{-6} \\times p \\times V}{R \\times T} \\hspace{75mm} (eq. 34),$$ ***Dissolution***\n\n$$CO_2(aq)^{*}[mmol] = \\beta \\times 10^{-6} \\times p \\times V_s \\times 10^{pK_H} \\hspace{75mm} (eq. 35),$$\n\n***Dissociation***\n\n$$HCO_3^-[mmol] = CO_2(aq)^{*} \\times 10^{pK_1 + pH} =\\beta \\times 10^{-6} \\times p \\times V_s \\times 10^{pK_H + pK_1 + pH} \\hspace{25mm} (eq. 36),$$\n\n$$CO_3^{-2}[mmol] = HCO_3^{-2} \\times 10^{pK_2 + pH} =\\beta \\times 10^{-6} \\times p \\times V_s \\times 10^{pK_H + pK_1 + pK_2 + 2 \\times pH} \\hspace{25mm} (eq. 37),$$\n\n***All forms of inorganic C***\n\n$$IC [mmol] = CO_{2}[mmol] + CO_2(aq)^{*}[mmol] + HCO_{3}^{-}[mmol] + CO_{3}^{-2}[mmol] = \\beta \\times 10^{-6} \\times p \\times [\\frac{V}{R \\times T} + V_s \\times (10^{pK_H} + 10^{pK_H + pK_1 + pH} + 10^{pK_H + pK_1 + pK_2 + 2 \\times pH}) ] \\hspace{10mm} (eq. 38).$$\n\nTo do so, we need to know $\\beta$ (measured by GC), atmospheric pressure ($p$), headspace volume ($V$), volume of soil water ($V_s$), temperature ($T$), soil pH, and the three experimentally derived constants $pK_H$, $pK_1$ and $pK_2$ whose values depend on $T$ according to eqs. 18, 32, and 33, respectively. If we first attempt to calculate the relative amount of all four IC forms in respect to total IC, $\\beta$ and $p$ do not need to be known. Let's assume again that $V = 100mL$, $V_s = 8 mL$, $T = 293.15K$, and soil pH may vary between 3 and 9. The relative amount of all IC forms in closed container along the pH gradient is shown in the graph below:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs-label\" for=\"Vs\">Volume of soil water (V<sub>s</sub>) in mL:</label>\n<input id=\"Vs\" type=\"number\" class=\"shiny-input-number form-control\" value=\"8\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"out3732861a04206e88\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 5***: *Distribution of relative amounts of* $CO_2(gas)$, $CO_2(aq)^{*}$, $HCO_3^{-}$ and $CO_3^{-2}$ along the gradient of soil pH\n\nTwo sources of variability must be explicitly highlighted:\n\n-   **Temperature**\n\nThe temperature significantly affects $CO_2$ solubility. The graph above representing a scenario for 20°C can be redrawn applying two other temperatures - 0 and 30°C. For simplicity, we will only plot $CO_2$ and $HCO_3^-$ as two dominant forms of IC.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V12-label\" for=\"V12\">Headspace volume (V) in mL:</label>\n<input id=\"V12\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs12-label\" for=\"Vs12\">Volume of soil water (V<sub>s</sub>) in mL:</label>\n<input id=\"Vs12\" type=\"number\" class=\"shiny-input-number form-control\" value=\"8\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp112-label\" for=\"Temp112\">Temperature 1 (T<sub>1</sub>) in K:</label>\n<input id=\"Temp112\" type=\"number\" class=\"shiny-input-number form-control\" value=\"273.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp212-label\" for=\"Temp212\">Temperature 2 (T<sub>2</sub>) in K:</label>\n<input id=\"Temp212\" type=\"number\" class=\"shiny-input-number form-control\" value=\"303.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"out01db6b8840d8bfc3\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 6***: *Distribution of relative amounts of gaseous* $CO_2$ and $HCO_3^{-}$ along the gradient of soil pH at three different temperatures 0, 20 and 30°C\n\nThe graph shows that the relative distribution of the two dominant IC forms changes with temperature. With increasing temperature, the relative amount of $CO_2$ increases.\n\n-   **Soil water content**\n\nThe volume of soil water is has a great effect, as the absence of water logically means absence of dissolved IC forms. We will redraw the figure 6 but this time, 0.1, 2 and 8 mL of soil water will be considered.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs1-label\" for=\"Vs1\">First volume of soil water (V<sub>s1</sub>) in mL:</label>\n<input id=\"Vs1\" type=\"number\" class=\"shiny-input-number form-control\" value=\"2\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs2-label\" for=\"Vs2\">Second volume of soil water (V<sub>s2</sub>) in mL:</label>\n<input id=\"Vs2\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.1\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"oute8127c14e22bc87f\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 7***: *Distribution of relative amounts of* $CO_2(gas)$ and $HCO_3^{-}$ along a gradient of soil pH at three different volumes of soil water 0.1, 2 and 8mL\n\nThe distribution of dominant IC forms changes dramatically. If soil water volume is very low, $CO_2$ dissolution is not relevant even at pH slightly above 7. It is, however, not recommended to incubate soil with such a low water content, because the soil microbial community may be water limited. We will use the last graph to visualize the relative error of IC underestimation in % if the $CO_2$ dissolution and further dissociation is completely neglected.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs1-label\" for=\"Vs1\">First volume of soil water (V<sub>s1</sub>) (green) in mL:</label>\n<input id=\"Vs1\" type=\"number\" class=\"shiny-input-number form-control\" value=\"2\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs2-label\" for=\"Vs2\">Second volume of soil water (V<sub>s2</sub>) (red) in mL:</label>\n<input id=\"Vs2\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.1\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"outde00e81d1ee89a93\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 8***: *Effect of soil pH and moisture on the relative error of IC estimation when* $CO_2(gas)$ is considered as a sole form of IC in the closed container.\n\nFigure 8 shows the importance of water content in incubation experiments (as we have seen in the chapter above), and that this effect increases with increasing pH. The headspace volume (or rather the ratio of $\\frac{V_s}{V}$) is also relevant. You can explore the effect by changing the headspace volume $V$ as well as the water content $V_s$ in the boxes above.\n\n#### Example: Temperature sensitivity of respiration (case 3)\n\nKnowing that different equilibrium constants have different temperature sensitivities, it may be interesting to further extend case 2. Since the distribution of IC species is strongly pH-dependent, the influence of $CO_2$ dissolution on $Q_{10}$ should be evaluated across a pH gradient (from 3 to 9). We will keep $Q_{10}^{app}$ (eq. 22) and its value (2) unchanged and assume again that $V = 100mL$, $V_s = 8 mL$, $T_1$ and $T_1$ are 20 and 30°C, respectively. Nevertheless, we need to redefine eq. 23 to acknowledge all IC forms:\n\n$$Q_{10} = Q_{10}^{app} \\times \\frac{T_2}{T_1} \\times \\frac{\\frac{V}{R \\times T_2} + V_s \\times (10^{pK_H(T_2)} + 10^{pK_H(T_2) + pK_1(T_2) + pH} + 10^{pK_H(T_2) + pK_1(T_2) + pK_2(T_2) + 2 \\times pH})}{\\frac{V}{R \\times T_1} + V_s \\times (10^{pK_H(T_1)} + 10^{pK_H(T_1) + pK_1(T_1) + pH} + 10^{pK_H(T_1) + pK_1(T_1) + pK_2(T_1) + 2 \\times pH})} \\hspace{10mm} (eq. 39).$$\n\nUsing eq. 39, $Q_{10}$ can be calculated for any soil pH:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs-label\" for=\"Vs\">Volume of soil water (V<sub>s</sub>) in mL:</label>\n<input id=\"Vs\" type=\"number\" class=\"shiny-input-number form-control\" value=\"8\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp1-label\" for=\"Temp1\">Temperature 1 (T<sub>1</sub>) in K:</label>\n<input id=\"Temp1\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp2-label\" for=\"Temp2\">Temperature 2 (T<sub>2</sub>) in K:</label>\n<input id=\"Temp2\" type=\"number\" class=\"shiny-input-number form-control\" value=\"303.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"outcaedddfd6d63a53b\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 9***: *The effect of soil pH on* $Q_{10}$ estimates calculated using eq. 39.\n\nThe graph in figure 9 shows that the temperature sensitivity of soil respiration originally estimated to be 2 (i.e. $Q_{10}^{app}$) may be actually lower when we consider the dissolution of $CO_2$ and further dissociation. It is further interesting to include another curve on this graph representing different temperature range - 0 and 10°C:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Vs-label\" for=\"Vs\">Volume of soil water (V<sub>s</sub>) in mL:</label>\n<input id=\"Vs\" type=\"number\" class=\"shiny-input-number form-control\" value=\"8\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp1-label\" for=\"Temp1\">Temperature 1 (T<sub>1</sub>) in K:</label>\n<input id=\"Temp1\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp2-label\" for=\"Temp2\">Temperature 2 (T<sub>2</sub>) in K:</label>\n<input id=\"Temp2\" type=\"number\" class=\"shiny-input-number form-control\" value=\"303.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp3-label\" for=\"Temp3\">Temperature 3 (T<sub>3</sub>) in K:</label>\n<input id=\"Temp3\" type=\"number\" class=\"shiny-input-number form-control\" value=\"273.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp4-label\" for=\"Temp4\">Temperature 4 (T<sub>4</sub>) in K:</label>\n<input id=\"Temp4\" type=\"number\" class=\"shiny-input-number form-control\" value=\"283.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"outa949008f8676da9b\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 10***: *Effect of soil pH on* $Q_{10}$ estimates calculated for two different temperature ranges, 0 - 10°C and 20 - 30°C; using eq. 39.\n\nFigure 10 shows that the variability in $Q_{10}$ decreases with decreasing temperature. The range of $Q_{10}$ values is lower when the temperature range of 0 to 10°C is considered. The extent of $Q_{10}$ underestimation increases strongly above pH \\~7.5, because $CO_2$ dissociates and forms to bicarbonates and carbonates at higher pH, reducing the amount of $CO_2$ in the container headspace.\n\nNote: Alkaline solutions with high pH, typically NaOH or KOH, are commonly used to trap $CO_2(gas)$. $CO_2(gas)$ is rapidly converted to bicarbonate and carbonate effectively removing it from the gas phase. This trapping mechanism is efficient as long as the solution remains alkaline. However, at high $CO_2$ loading, the solution capacity to trap $CO_2(gas)$ will be exceeded, causing the pH to drop. To release the trapped $CO_2$, the solution is can be acidified shifting the equilibrium back toward $CO_2(gas)$. Amount of trapped $CO_2(gas)$ can be either determined from the change of solution conductivity or alkalinity (i.e. by estimating the residual amount of alkali).\n\n#### Example: Microbial physiology metrics (case 4)\n\nRespiration rate is one of the most important variables that is used to infer various metrics of microbial physiology such as the metabolic quotient (MMQ), respiratory quotient (RQ) or carbon use efficiency (CUE). Similarly to the example cases 1 to 3, $CO_2$ dissolution and dissociation can compromise accuracy of these metrics. MMQ and RQ have respiration rate (R) in the nominator:\n\n$$MMQ = \\frac{R}{MBC} \\hspace{75mm} (eq. 40),$$ $~$ $$RQ = \\frac{R}{O_2 ~ consumption} \\hspace{75mm} (eq. 41).$$\n\nIn eqs. 40 and 41, $MBC$ is microbial biomass carbon and $O_2 ~ consumption$ denotes oxygen consumption rate. Assuming, for simplicity, no change in $MBC$ and $O_2 ~ consumption$ along the pH gradient, the relative error of both metrics is caused by unaccounted $CO_2$ dissolution and further dissociation and can be expressed as:\n\n$$Error[\\%] = [1 - \\frac{V}{V + R \\times T \\times V_s \\times (10^{pK_H} + 10^{pK_H + pK_1 + pH} + 10^{pK_H + pK_1 + pK_2 + 2 \\times pH})}] \\times 100 \\hspace{10mm} (eq. 42).$$\n\nThe following graph shows the relative error for three different water contents $V_s$ of 0.1, 2 and 8 mL while assuming $V = 100mL$ and $T = 293.15K$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"outb810d33501214592\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 11***: *Effect of soil pH on relative error (in %) of MMQ and RQ estimates calculated for three different volumes of soil water (0.1, 2 and 8 mL) using eq. 42.*\n\nSince the error solely depends on change of IC in soil water, figure 11 is essentially the same as figure 8.\n\nThe situation is slightly different for CUE because R is in the denominator:\n\n$$CUE = \\frac{\\Delta MBC}{\\Delta MBC + R} \\hspace{75mm} (eq. 43).$$\n\nIn equation 43, $\\Delta MBC$ is the change of MBC over time in the same units as R (i.e. no death rate of microbial biomass is assumed). The relative error can be defined with following equation:\n\n$$Error[\\%] = \\left\\{ \\frac{\\Delta MBC + \\Delta \\beta \\times 10^{-6} \\times p \\times [ \\frac{V}{R \\times T} + V_s \\times (10^{pK_H} + 10^{pK_H + pK_1 + pH} + 10^{pK_H + pK_1 + pK_2 + 2 \\times pH}) ]}{\\Delta MBC + \\frac{ \\Delta \\beta \\times 10^{-6} \\times p \\times V}{R \\times T}} - 1 \\right\\} \\times 100  \\hspace{10mm} (eq. 44).$$\n\nThe equation implies that the change in partial $CO_2$ pressure ($\\Delta \\beta \\times 10^{-6} \\times p$) needs to be defined to allow the calculation as the amount of produced $CO_2$ is compared to $\\Delta MBC$. To simplify the equation, we need to link $\\Delta \\beta \\times 10^{-6} \\times p$ to $\\Delta MBC$. The most reliable approach is to use an assumption that respiration equals change in $\\Delta MBC$:\n\n$$\\Delta \\beta \\times 10^{-6} \\times p \\times [\\frac{V}{R \\times T} + V_s \\times (10^{pK_H} + 10^{pK_H + pK_1 + pH} + 10^{pK_H + pK_1 + pK_2 + 2 \\times pH})] = \\Delta MBC \\hspace{10mm} (eq. 45).$$\n\nWe are assuming that CUE is 0.5 when all forms of IC are accounted for and that $\\Delta MBC$ is the same for all values of soil pH. Combining eqs. 44 and 45, we get:\n\n$$Error[\\%] = \\left\\{\\frac{\\Delta MBC + \\Delta MBC}{\\Delta MBC + \\Delta MBC \\times \\frac{V}{R \\times T \\times [\\frac{V}{R \\times T} + V_s \\times (10^{pK_H} + 10^{pK_H + pK_1 + pH} + 10^{pK_H + pK_1 + pK_2 + 2 \\times pH})]}}-1 \\right\\} \\times 100 = [\\frac{2}{1 + \\frac{V}{V + R \\times T \\times V_s \\times (10^{pK_H} + 10^{pK_H + pK_1 + pH} + 10^{pK_H + pK_1 + pK_2 + 2 \\times pH})}}-1]\\times 100 \\hspace{10mm} (eq. 46).$$\n\nApplying eq. 46, we can plot the relative error of CUE estimation for the three different scenarios of 0.1, 2 and 8 mL volume of soil water while assuming $V = 100mL$ and $T = 293.15K$ again.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V-label\" for=\"V\">Headspace volume (V) in mL:</label>\n<input id=\"V\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp-label\" for=\"Temp\">Temperature in K:</label>\n<input id=\"Temp\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"out15507ee028542ee7\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 12***: *Effect of soil pH on relative error (in %) of CUE estimates calculated for three different volumes of soil water (0.1, 2 and 8mL) using eq. 46.*\n\nThe relative error of CUE estimation is similarly to MMQ and RQ more than 90% at high soil pH and $V_s$.\n\n# Confounding effects of soil solution chemistry\n\nThe extent of dissolution of $CO_2(gas)$ in soil water and further dissociation to $HCO_3^{-}$ and $CO_3^{-2}$ is affected by chemical composition of soil solution. The presence of various charged chemical species in soil solution directly affects Henry's law constant $pK_H$ and activity of $H^+$, $HCO_3^{-}$ and $CO_3^{-2}$. It is thus necessary to extend the theory further to acknowledge the effect of soil solution chemistry. In next two sections, we will first discuss the activity of $H^+$, $HCO_3^{-}$ and $CO_3^{-2}$ by applying Debye–Hückel equation because the respective mathematical expression is not that difficult to grasp. Then, we will explain the effect of soil solution chemistry on $pK_H$ by applying Sechenov relationship in its extended form as presented by Weisenberger and Schumpe (1996).\n\n## Estimating activity coefficients using the Debye–Hückel equation\n\nThere is a difference between the concentration and the activity of charged species including $HCO_3^-$, $CO_3^{-2}$ and $H^+$. While the concentration refers to the amount of substance per unit volume (e.g. $mol \\times  L^{-1}$), the activity reflects the effective concentration, accounting for interactions between ions in solution. These interactions are significant for all charged species, including $H^+$, $HCO_3^-$, $CO_3^{-2}$, and other cations and anions. The relationship between activity and concentration is defined by an equation:\n\n$$a_s = \\gamma_s \\times [S] \\hspace{75mm} (eq. 47),$$\n\nin which $a_s$ is an activity of charged species of interest, $[S]$ is its concentration in $mol \\times L^{-1}$, and $\\gamma_s$ is nondimensional activity coefficient. The constants $pK_1$ and $pK_2$ have been defined for activities of charged species, not concentrations. It is therefore important to determine what could be the error of our calculations when we ignore activity coefficients. To do so, we need to calculate activity coefficients first. This can be achieved by using Debye-Huckel equation:\n\n$$log(\\gamma_i) = - \\frac{A \\times z_i^2 \\times \\sqrt I}{1 + B \\times \\alpha_i \\times \\sqrt I} \\hspace{75mm} (eq. 48),$$\n\nin which $z_i$ is charge of ion $i$, $\\alpha_i$ is its effective size in Angstroms (i.e. 1A = 0.1 nm), $I$ is the ionic strength of soil solution in $mol \\times L^{-1}$, $A$ and $B$ are coefficients of the equation with dimensions $\\frac{L^{0.5}}{mol^{0.5}}$ and $\\frac{L^{0.5}}{A \\times mol^{0.5}}$, respectively. There are five different variables in eq. 48, which needs to be known to calculate $\\gamma_{i}$. One that can be directly calculated is $I$ because:\n\n$$I = \\frac{1}{2} \\times \\sum c_i \\times z_i^2 \\hspace{75mm} (eq. 49).$$\n\nIn eq. 49, $c_i$ is the concentration of ion $i$ in $mol \\times L^{-1}$ and $z_i$ is its charge. Let us to apply this equation to the ion composition of a soil solution reported in Stednick (1984):\n\n|     Ion     | Charge | Concentrations in $\\mu mol \\times L^{-1}$ |\n|:-----------:|:------:|:-----------------------------------------:|\n|    $H^+$    |   1    |                    1.6                    |\n|    $K^+$    |   1    |                    15                     |\n|  $Ca^{+2}$  |   2    |                    40                     |\n|  $Mg^{+2}$  |   2    |                   23.5                    |\n|   $Na^+$    |   1    |                    96                     |\n|  $Fe^{+2}$  |   2    |                    0.3                    |\n| $SO_4^{-2}$ |   2    |                    130                    |\n|   $Cl^-$    |   1    |                    273                    |\n\nIn this case, the ionic strength (in $mol \\times L^{-1}$) is:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"H-label\" for=\"H\">H<sup>+</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"H\" type=\"number\" class=\"shiny-input-number form-control\" value=\"1.6\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"K-label\" for=\"K\">K<sup>+</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"K\" type=\"number\" class=\"shiny-input-number form-control\" value=\"15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Ca-label\" for=\"Ca\">Ca<sup>+2</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"Ca\" type=\"number\" class=\"shiny-input-number form-control\" value=\"40\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Mg-label\" for=\"Mg\">Mg<sup>+2</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"Mg\" type=\"number\" class=\"shiny-input-number form-control\" value=\"23.5\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Na-label\" for=\"Na\">Na<sup>+</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"Na\" type=\"number\" class=\"shiny-input-number form-control\" value=\"96\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Fe-label\" for=\"Fe\">Fe<sup>+2</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"Fe\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.3\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"SO4-label\" for=\"SO4\">SO<sub>4</sub><sup>-2</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"SO4\" type=\"number\" class=\"shiny-input-number form-control\" value=\"130\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Cl-label\" for=\"Cl\">Cl<sup>-</sup> (&micromol L<sup>-1</sup>) :</label>\n<input id=\"Cl\" type=\"number\" class=\"shiny-input-number form-control\" value=\"273\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"outf10a9501c9cf591a\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$$I = \\frac{1 \\times 10^{-6}}{2} \\times (1.6 \\times 1^2 + 15 \\times 1^2 + 40 \\times 2^2 + 23.5 \\times 2^2 + 96 \\times 1^2 + 0.3 \\times 2^2 + 130 \\times 2^2 + 273 \\times 1^2) = 5.8 \\times 10^{-4}  \\hspace{75mm} (eq. 50).$$\n\nNote that pH of this soil is $-log(1.6 \\times 10^{-6}) = 5.8$. With increasing soil pH, the concentration of $H^+$ decreases accordingly (i.e. concentration of $OH^-$ is neglected here for the simplicity) and the concentrations of $HCO_3^-$ and $HO_3^{-2}$ will increase. At this point, however, we will just ignore change in $HCO_3^-$ and $HO_3^{-2}$ to simplify the example.\n\nCoefficients A and B are experimentally derived constants (Hamer, 1968). Their values depend on dielectric constant of water, water density and, most importantly, temperature. For the sake of simplicity, we we will stick to our example assuming a temperature of 20°C. At this temperature, coefficients A and B are $0.5072 \\frac{L^{0.5}}{mol^{0.5}}$ and $0.3282 \\frac{L^{0.5}}{A \\times mol^{0.5}}$, respectively. Lastly we have to define the effective ion size ($\\alpha_i$), which is $5.4A$ for $HCO_3^-$ and $CO_3^{-2}$, and $9A$ for $H^+$. At 20°C, the activity coefficients $\\gamma_{HCO_3^-}$, $\\gamma_{CO_3^{-2}}$ and $\\gamma_{H^+}$ in a soil with ionic strength $5.8 \\times 10^{-4}~mol \\times L^{-1}$ are:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"A-label\" for=\"A\">Equation coefficient A :</label>\n<input id=\"A\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.5072\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"B-label\" for=\"B\">Equation coefficient B :</label>\n<input id=\"B\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.3282\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"alphaIC-label\" for=\"alphaIC\">Effective ion size of HCO<sub>3</sub><sup>-</sup> and CO<sub>3</sub><sup>-2</sup> (&alpha;<sub>HCO<sub>3</sub><sup>-</sup></sub> and &alpha;<sub>CO<sub>3</sub><sup>-2</sup></sub> in A)  :</label>\n<input id=\"alphaIC\" type=\"number\" class=\"shiny-input-number form-control\" value=\"5.4\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"alphaH-label\" for=\"alphaH\">Effective ion size of H<sup>+</sup> (&alpha;<sub>H<sup>+</sup></sub> in A)  :</label>\n<input id=\"alphaH\" type=\"number\" class=\"shiny-input-number form-control\" value=\"9\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"I-label\" for=\"I\">Ionic strength of soil solution (I in mol L<sup>-1</sup>) :</label>\n<input id=\"I\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.00058\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"out982d1c4386fc3fec\" class=\"shiny-html-output\"></div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"out5fb094d396972397\" class=\"shiny-html-output\"></div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"out27262196ba770e04\" class=\"shiny-html-output\"></div>\n```\n\n:::\n:::\n\n\n$$\\gamma_{HCO_3^-} = 10^{- \\frac{0.507 \\times 1^2 \\times \\sqrt 5.8 \\times 10^{-4}}{1 + 0.3282 \\times 5.4 \\times \\sqrt 5.8 \\times 10^{-4}}} = 0.97 \\hspace{75mm} (eq. 51),$$\n\n$$\\gamma_{CO_3^{-2}} = 10^{- \\frac{0.507 \\times 2^2 \\times \\sqrt 5.8 \\times 10^{-4}}{1 + 0.3282 \\times 5.4 \\times \\sqrt 5.8 \\times 10^{-4}}} = 0.90 \\hspace{75mm} (eq. 52),$$\n\n$$\\gamma_{H^{+}} = 10^{- \\frac{0.507 \\times 1^2 \\times \\sqrt 5.8 \\times 10^{-4}}{1 + 0.3282 \\times 9 \\times \\sqrt 5.8 \\times 10^{-4}}} = 0.97 \\hspace{75mm} (eq. 53),$$\n\nFor $HCO_3^-$ and $H^+$, the activity is almost the same as concentration. Nevertheless, the activity of $CO_3^{-2}$ is lower by 10% than the concentration.\n\n## Approximating activity coefficients using electrical conductivity of soil solution\n\nAs it is impractical to measure all charged species in soil solution to calculate $I$, a more straightforward approach is to measure electrical conductivity of soil solution and use its value to calculate $I$ using an equation defined by Alva et al. (1991):\n\n$$I[mol \\times L^{-1}] = 0.015 \\times EC[mS \\times cm^{-1}] - 6 \\times 10^{-4} \\hspace{75mm} (eq. 54),$$ in which $EC$ is the measured electrical conductivity of a soil solution in $mS \\times cm^{-1}$. Across various soils exposed to various treatments, Alva et al. (1991) reported $I$ to range between 0 and 0.25 $mol \\times L^{-1}$. We will calculate and plot $\\gamma_{HCO_3^-}$, $\\gamma_{CO_3^{-2}}$ and $\\gamma_{H^+}$ across that range of $I$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"A-label\" for=\"A\">Equation coefficient A :</label>\n<input id=\"A\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.5072\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"B-label\" for=\"B\">Equation coefficient B :</label>\n<input id=\"B\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.3282\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"alphaIC-label\" for=\"alphaIC\">Effective ion size of HCO<sub>3</sub><sup>-</sup> and CO<sub>3</sub><sup>-2</sup> (&alpha;<sub>HCO<sub>3</sub><sup>-</sup></sub> and &alpha;<sub>CO<sub>3</sub><sup>-2</sup></sub> in A)  :</label>\n<input id=\"alphaIC\" type=\"number\" class=\"shiny-input-number form-control\" value=\"5.4\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"alphaH-label\" for=\"alphaH\">Effective ion size of H<sup>+</sup> (&alpha;<sub>H<sup>+</sup></sub> in A)  :</label>\n<input id=\"alphaH\" type=\"number\" class=\"shiny-input-number form-control\" value=\"9\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"outd703f16100533d8b\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 13***: *The effect of the ionic strength of a soil solution on the activity coefficients* $\\gamma_i$ of $HCO_3^{-}$, $CO_3^{-2}$ and $H^{+}$ (see eqs. 51 - 53).\n\nAt high $I$, activity coefficients could be very low.\n\nKnowing that activity coefficients can have substantial effect, we will redefine eqs. 28 - 31:\n\n$$K^1 = \\frac{\\gamma_{H^+} \\times H^+ \\times \\gamma_{HCO_3^-} \\times HCO_3^-}{CO_2(aq)^{*}} \\hspace{75mm} (eq. 55),$$\n\n$$K^2 = \\frac{\\gamma_{H^+} \\times H^+ \\times \\gamma_{CO_3^{-2}} \\times CO_3^{-2}}{\\gamma_{HCO_3^-} \\times HCO_3^-} \\hspace{75mm} (eq. 56),$$\n\nand\n\n$$log(HCO_3^-) = pK_1 + pH + log(CO_2(aq)^{*}) - log(\\gamma_{H^+}) - log(\\gamma_{HCO_3^-}) \\hspace{75mm} (eq. 57),$$\n\n$$log(CO_3^{-2}) = pK_2 + pH + log(HCO_3^-) - log(\\gamma_{H^+}) + log(\\gamma_{HCO_3^-}) - log(\\gamma_{CO_3^{-2}}) \\hspace{75mm} (eq. 58).$$\n\nTo be rigorous, we can also account for non-ideal behavior of $CO_2$ using a fugacity coefficient $\\gamma_{CO_2}$, which has the similar meaning as the activity coefficient, and it is defined by an equation:\n\n$$ln(\\gamma_{CO_2}) = \\frac{1}{R \\times T \\times (0.10476 - 61.0102 \\times \\frac{1}{T} - 660000 \\times \\frac{1}{T^3} - 2.47 \\times 10^{27} \\times \\frac{1}{T^{12}})}  \\hspace{75mm} (eq. 59).$$\n\nThe concentration of $CO_2(aq)^{*}$ could be multiplied by $\\gamma_{CO_2}$ whose value between 0 - 50°C is shown on following graph:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](respiration_files/figure-html/Rscript (24) plotting fugacity coefficients of CO2 along the gradient of temperature applying eq. 59-1.png){width=672}\n:::\n:::\n\n\n***Figure 14***: *Relationship between the temperature and fugacity coefficient of* $CO_2$ (see eq. 59).\n\nAs suggested by figure 14, we can simply assume that $\\gamma_{CO_2} = 1$ in all calculations without causing a substantial error.\n\nWe will update figure 8 by adding three additional lines to account for the effect of soil solution ionic strength of 0.25 $mol \\times L^{-1}$ on $CO_2$ solubility. For the sake of simplicity, we will assume that ionic strength remains constant with pH. Eqs. 34 and 35 do not change, but eqs. 36 - 38 do (according to eqs. 57 and 58):\n\n$$HCO_3^- [mmol] = \\beta \\times 10^{-6} \\times p \\times V_s \\times 10^{pK_H + pK_1 + pH - log(\\gamma_{H^+}) - log(\\gamma_{HCO_3^-})} \\hspace{25mm} (eq. 60),$$\n\n$$CO_3^{-2} [mmol] = \\beta \\times 10^{-6} \\times p \\times V_s \\times 10^{pK_H + pK_1 + pK_2 + 2 \\times pH - 2 \\times log(\\gamma_{H^+}) - log(\\gamma_{CO_3^{-2}})} \\hspace{25mm} (eq. 61),$$\n\n$$IC [mmol] = \\beta \\times 10^{-6} \\times p \\times [\\frac{V}{R \\times T} \\times V_s \\times (10^{pK_H} + 10^{pK_H + pK_1 + pH - log(\\gamma_{H^+}) - log(\\gamma_{HCO_3^-})} + 10^{pK_H + pK_1 + pK_2 + 2 \\times pH - 2 \\times log(\\gamma_{H^+}) - log(\\gamma_{CO_3^{-2}})})] \\hspace{25mm} (eq. 62).$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"V25-label\" for=\"V25\">Headspace volume (V) in mL:</label>\n<input id=\"V25\" type=\"number\" class=\"shiny-input-number form-control\" value=\"100\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"Temp25-label\" for=\"Temp25\">Temperature in K:</label>\n<input id=\"Temp25\" type=\"number\" class=\"shiny-input-number form-control\" value=\"293.15\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"form-group shiny-input-container\">\n<label class=\"control-label\" id=\"IS-label\" for=\"IS\">Ionic strength in mol L<sup>1</sup>:</label>\n<input id=\"IS\" type=\"number\" class=\"shiny-input-number form-control\" value=\"0.25\" data-update-on=\"change\"/>\n</div>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"shiny-plot-output html-fill-item\" id=\"out30febdb1a1ccb52b\" style=\"width:100%;height:400px;\"></div>\n```\n\n:::\n:::\n\n\n***Figure 15***: *The effect of soil ionic strength, pH and moisture on the relative error of IC estimation when* $CO_2$ is considered as a sole form of IC in the closed container.\n\nAs shown on figure 15, the relative error of IC estimation increases when corrections for soil solution ionic strength (being relatively high in this exercise) are applied. However, the increase is not substantial when compared to the variability of the error along the pH gradient. By manipulating parameter the box for ionic strength, the graph can be redrawn for any value of ionic strength. The key point, which we would like to document here is that accounting for $CO_2$ dissolution inaccurately using eqs. 34 - 37 is more useful than trying to do the calculation as accurately as possible. There is one more confounding effect of soil solution chemistry, which will be discussed in following section.\n\n## Estimating effect of soil solution chemistry on $pK_H$ using Sechenov relationship\n\nThe concentration of ions in soil solution affects not only the activity coefficients but also the solubility of $CO_2$ through Henry's law constant $pK_H$. Unfortunately, the mathematical expression of this effect is difficult to apply accurately in case of soil solution, because several different ions are typically present in there. The general relationship between $pK_H$ and concentration of ions in soil solution is defined by following equation:\n\n$$pK_H = pK_{H,0} - \\sum[h_i + h_{G,0} + h_T \\times (T-298.15)] \\times c_i \\hspace{75mm} (eq. 63).$$\n\nin which $pK_{H,0}$ is Henry's law constant for pure water (eq. 18), $pK_H$ is the constant for a solution that contains several ions ($i$). Concentration of each ion in $mol \\times L^{-1}$ is defined by variable $c_i$ and its effect on $pK_H$ is defined by a empirically estimated parameter $h_i$ in $L \\times mol^{-1}$. Finally, variables $h_{G,0}$ (in $L \\times mol^{-1}$) and $h_T$ (in $L \\times mol^{-1} \\times K^{-1}$) are two gas specific (i.e. $CO_2$ specific in this case) variables, again experimentally derived. The first applies to standard temperature 298.15 °C, and the second defines the temperature sensitivity. Every gas has its own $h_{G,0}$ and $h_T$, and every ion present in soil solution has its own $h_i$. Eq. 63 cannot be applied if concentrations of all ions in soil solution are not known. This is the reason for why the eq. 63 is so difficult to use. Concentrations of all ions in soil solution is rarely known and that limits the use of eq. 63. We will use the data of Stednick (1984) reported above to quantify the effect of soil solution chemistry on $pK_H$.\n\nAccording to Weisenberger and Schumpe (1996), $CO_2$ specific variables $h_{G,0}$ and $h_T$ are respectively $-0.0172~L \\times mol^{-1}$ and $-0.338 \\times 10^{-3}~L \\times mol^{-1}$. At 20°C (293.15 K), $-0.0172 - 0.338 \\times 10^{-3} \\times (293.15 - 298.15) = -0.01551$ is added to all $h_i$ of all ions in soil solution. Values of $h_i$ of each ion measured by Stednick (1984) in soil solution are reported in the table below.\n\n| Ion | $h_i$ in $L \\times mol^{-1}$ | Concentrations in $\\mu mol \\times L^{-1}$ |\n|:----------------------:|:----------------------:|:----------------------:|\n| $H^+$ | 0 | 1.6 |\n| $K^+$ | 0.0922 | 15 |\n| $Ca^{+2}$ | 0.1762 | 40 |\n| $Mg^{+2}$ | 0.1694 | 23.5 |\n| $Na^+$ | 0.1143 | 96 |\n| $Fe^{+2}$ | 0.1523 | 0.3 |\n| $SO_4^{-2}$ | 0.1172 | 130 |\n| $Cl^-$ | 0.0318 | 273 |\n\nAccording to eq. 18, $pK_{H,0}$ is -1.41 at 20°C. Applying the eq. 63, $pK_H$ is expected to be:\n\n$$pK_H = -1.41 - [(0 -0.01551) \\times 1.6 \\times 10^{-6} \\hspace{20mm} (H^+)\\\\\n     \\hspace{20mm} + (0.0922 -0.01551) \\times 15 \\times 10^{-6} \\hspace{20mm} (K^+) \\\\\n   \\hspace{20mm} + (0.1762 -0.01551) \\times 40 \\times 10^{-6} \\hspace{20mm} (Ca^{+2}) \\\\\n   \\hspace{20mm} + (0.1694 -0.01551) \\times 23.5 \\times 10^{-6} \\hspace{20mm} (Mg^{+2}) \\\\\n   \\hspace{20mm} + (0.1143 -0.01551) \\times 96 \\times 10^{-6} \\hspace{20mm} (Na^{+}) \\\\\n   \\hspace{20mm} + (0.1523 -0.01551) \\times 0.3 \\times 10^{-6} \\hspace{20mm} (Fe^{+2}) \\\\\n   \\hspace{20mm} + (0.1172 -0.01551) \\times 130 \\times 10^{-6} \\hspace{20mm} (SO_4^{-2}) \\\\\n   \\hspace{20mm} + (0.0318 -0.01551) \\times 273 \\times 10^{-6} \\hspace{20mm} (Cl^{-}) \\\\\n   \\hspace{20mm} = -1.41 - 5.52 \\times 10^{-5} \\approx -1.41 \\hspace{20mm} (eq. 64)$$\n\nThe effect of soil solution chemistry on $pK_H$ is negligible in this case. Eq. 63 is typically used to calculate $CO_2$ solubility in see water with nearly molar concentrations of $Na^+$ and $Cl^-$. Thus, the effect of soil solution chemistry on $pK_H$ could be neglected in most of soils. This effect, however, becomes significant in very saline soils or in soils. Let's document it on an example.\n\nIn the following example, we will use eq. 63 to calculate $pK_H$ of $CO_2$ for dry steppe solonetz using measured ion concentrations reported in Endovitsky et al. (2014). The ion concentrations are reported in a table below:\n\n| Ion | $h_i$ in $L \\times mol^{-1}$ | Concentrations in $mmol \\times L^{-1}$ |\n|:----------------------:|:----------------------:|:----------------------:|\n| $HCO_3^-$ | 0.0967 | 8.88 |\n| $CO_3^{-2}$ | 0.1423 | 0.72 |\n| $Ca^{+2}$ | 0.1762 | 9.73 |\n| $Mg^{+2}$ | 0.1694 | 77.5 |\n| $Na^+$ | 0.1143 | 270.4 |\n| $SO_4^{-2}$ | 0.1172 | 137.2 |\n| $Cl^-$ | 0.0318 | 160.2 |\n\nAccording to reported soil solution composition, $pK_H$ at 20°C is expected to be:\n\n$$pK_H = -1.41 - [(0.0967 -0.01551) \\times 8.88 \\times 10^{-3} \\hspace{20mm} (HCO_3^-)\\\\\n     \\hspace{20mm} + (0.1423 -0.01551) \\times 0.72 \\times 10^{-3} \\hspace{20mm} (CO_3^{-2}) \\\\\n   \\hspace{20mm} + (0.1762 -0.01551) \\times 9.73 \\times 10^{-3} \\hspace{20mm} (Ca^{+2}) \\\\\n   \\hspace{20mm} + (0.1694 -0.01551) \\times 77.5 \\times 10^{-3} \\hspace{20mm} (Mg^{+2}) \\\\\n   \\hspace{20mm} + (0.1143 -0.01551) \\times 270.4 \\times 10^{-3} \\hspace{20mm} (Na^{+}) \\\\\n   \\hspace{20mm} + (0.1172 -0.01551) \\times 137.2 \\times 10^{-3} \\hspace{20mm} (SO_4^{-2}) \\\\\n   \\hspace{20mm} + (0.0318 -0.01551) \\times 160.2 \\times 10^{-3} \\hspace{20mm} (Cl^{-}) \\\\\n   \\hspace{20mm} = -1.41 - 0.0576 = -1.468 \\hspace{20mm} (eq. 65)$$\n\nAs compared to $pK_{H,0}$, $pK_H$ is lower so the $CO_2$ solubility decreases in this saline soil by $(1 - 10^{-1.468 + 1.41}) \\times 100 = 12.5 \\%$. Nevertheless, the salinity also affects the dissociation due to high ionic strength of the solution. Let's compare decrease in solubility with the effect of high ionic strength on the dissociation. To perform the comparison, we need to calculate ionic strength of soil solution using eq. 49:\n\n$$I = \\frac{1 \\times 10^{-3}}{2} \\times (8.88 \\times 1^2 [HCO_3^{-}] + 0.72 \\times 2^2 [CO_3^{-2}] + 9.73 \\times 2^2 [Ca^{+2}]+ 77.5 \\times 2^2[Mg^{+2}] + 270.4 \\times 1^2 [Na^+] + 137.4 \\times 2^2 [SO_4^{-2}] + 16.2 \\times 1^2 [Cl^-]) = 0.6~mol \\times L  \\hspace{75mm} (eq. 66).$$ Knowing the ionic strength, we can further calculate activity coefficients $\\gamma_{HCO_3^-}$, $\\gamma_{CO_3^{-2}}$ and $\\gamma_{H^+}$ using eqs. 51 - 53:\n\n$$\\gamma_{HCO_3^-} = 10^{- \\frac{0.507 \\times 1^2 \\times \\sqrt 0.6}{1 + 0.3282 \\times 5.4 \\times \\sqrt 0.6}} = 0.68 \\hspace{75mm} (eq. 67),$$\n\n$$\\gamma_{CO_3^{-2}} = 10^{- \\frac{0.507 \\times 2^2 \\times \\sqrt 0.6}{1 + 0.3282 \\times 5.4 \\times \\sqrt0.6}} = 0.22 \\hspace{75mm} (eq. 68),$$\n\n$$\\gamma_{H^{+}} = 10^{- \\frac{0.507 \\times 1^2 \\times \\sqrt 0.6}{1 + 0.3282 \\times 9 \\times \\sqrt 0.6}} = 0.76 \\hspace{75mm} (eq. 69),$$\n\nFinally, we can quantify the relative change in the amount of IC in soil solution with a composition reported above and pH of 8.85 as compared to pure water using an equation:\n\n$$\\Delta IC [\\%] =(\\frac{10^{pK_H} + 10^{pK_H + pK_1 + pH - log(\\gamma_{H^+}) - log(\\gamma_{HCO_3^-})} + 10^{pK_H + pK_1 + pK_2 + 2\\times pH - 2 \\times log(\\gamma_{H^+}) - log(\\gamma_{CO_3^{-2}})}}{10^{pK_{H, 0}} + 10^{pK_{H, 0} + pK_1 + pH} + 10^{pK_{H, 0} + pK_1 + pK_2 + 2\\times pH}} - 1) \\times 100 = 84 \\% \\hspace{20mm} (eq. 70).$$\n\nThe effect of ionic strength on total IC in soil solution through its effect on activity coefficients is greater than the effect of soil solution composition through its effect on $pK_H$. Even though the high concentration of ions in soil solution reduces solubility of $CO_2$, it increases the magnitude of dissociation relatively more. Neglecting the effect of composition of soil solution will cause underestimation of total IC rather than overestimation. On the other hand, if we decide to correct our calculations for ionic strength effect only because it is easier to calculate, our results will be overestimated by approx. 30%. Due to such complexity, it is recommended not to use gas chromatography when respiration rate is measured in highly saline soils. Instead, older and, unfortunately, more tedious method of soil incubation with cup containing strong alkali is recommended.\n\n# References\n\nAlva, A.K., Sumner, M.E., Miller, W.P., 1991. Relationship between ionic strength and electrical conductivity for soil solutions. Soil Science 152, 239.\n\nČapek, P., Diáková, K., Dickopp, J.E., Bárta, J., Wild, B., Schnecker, J., Alves, R.J.E., Aiglsdorfer, S., Guggenberger, G., Gentsch, N., Hugelius, G., Lashchinsky, N., Gittel, A., Schleper, C., Mikutta, R., Palmtag, J., Shibistova, O., Urich, T., Richter, A., Šantrůčková, H., 2015. The effect of warming on the vulnerability of subducted organic carbon in arctic soils. Soil Biology & Biochemistry 90, 19–29. https://doi.org/10.1016/j.soilbio.2015.07.013\n\nDilly, O., 2001. Microbial respiratory quotient during basal metabolism and after glucose amendment in soils and litter. Soil Biology & Biochemistry 33, 117–127. https://doi.org/10.1016/s0038-0717(00)00123-1\n\nDilly, O., 2003. Regulation of the respiratory quotient of soil microbiota by availability of nutrients. FEMS Microbiology Ecology 43, 375–381. https://doi.org/10.1016/s0168-6496(02)00437-3\n\nDilly, O., 2004. Effects of glucose, cellulose, and humic acids on soil microbial eco-physiology. Journal of Plant Nutrition and Soil Science 167, 261–266. https://doi.org/10.1002/jpln.200321041\n\nEndovitsky, A.P., Minkina, T.M., Kalinichenko, V.P., Batukaev, A.A., Dikaev, Z.S., Sushkova, S.N., 2014. THE ASSOCIATION OF IONS IN THE SOIL SOLUTION OF SALINE SOILS. AJABS 9, 238–244. https://doi.org/10.3844/ajabssp.2014.238.244\n\nHamer, W.J., 1968. Theoretical Mean Activity Coefficients of Strong Electrolytes in Aqueous Solutions from 0 to 100 C (No. NASA-CR-109356).\n\nPlummer, L.N., Busenberg, E., 1982. The solubilities of calcite, aragonite and vaterite in CO2-H2O solutions between 0 and 90°C, and an evaluation of the aqueous model for the system CaCO3-CO2-H2O. Geochimica et Cosmochimica Acta 46, 1011–1040. https://doi.org/10.1016/0016-7037(82)90056-4\n\nStednick, J.D., 1984. Soil solution chemistry in a Southeast Alaska spodosol suggests positively charged organic compounds. Water Air Soil Pollut 23, 263–269. https://doi.org/10.1007/BF00283203\n\nWeisenberger, S., Schumpe, A., 1996. Estimation of gas solubilities in salt solutions at temperatures from 273 K to 363 K. AIChE Journal 42, 298–300. https://doi.org/10.1002/aic.690420130\n",
    "supporting": [
      "respiration_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}